### ISSUE TITLE
Usage with Apollo Graphql Query

### ISSUE THREAD

**Issue by pavanmehta91** [jamesplease/react-composer#61]
Using Composer with Apollo Graphql Query render prop throws a warning that this.props.children is a required prop for a Query render prop and I guess Composer is not passing in any. Although this does not break any functionality but It'd be nice to remove that error.

**Comment by jamesplease** [comment]
This is covered [in the README](
https://github.com/jamesplease/react-composer#console-warnings).

**Comment by pavanmehta91** [comment]
Sorry my bad. Thanks for that 👍
